# Generated by Django 3.1.5 on 2021-04-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('createpass', models.CharField(max_length=50, null=True)),
                ('confirmpass', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
