# Generated by Django 3.0.6 on 2021-04-17 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('speciality', models.CharField(choices=[('Allergist', 'Allergist'), ('Immunologists', 'Immunologists'), ('Anesthesiologists', 'Anesthesiologists'), ('Cardiologists', 'Cardiologists'), ('Neurologists', 'Neurologists'), ('Colon and Rectal Surgeons', 'Colon and Rectal Surgeons'), ('Radiologists', 'Radiologists'), ('Physician', 'Physician')], max_length=50)),
                ('availablity', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('symptoms', models.CharField(choices=[('Fever', 'Fever'), ('Body Ache', 'Body Ache'), ('Cold', 'Cold'), ('Cough', 'Cough'), ('Difficulty in Breathing', 'Difficulty in Breathing'), ('Loss in smell and taste', 'Loss in smell and taste')], max_length=200, null=True)),
                ('severity', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('medicine', models.TextField(max_length=100, null=True)),
                ('diet', models.TextField(max_length=500, null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='healthcare1.Doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='healthcare1.Patient')),
            ],
        ),
    ]
